spring.application.name=OnlineStore

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stripe.api.key=${STRIPE_KEY}


spring.ai.openai.base-url=http://localhost:12434/engines
spring.ai.openai.api-key=unused
spring.ai.openai.chat.options.model=docker.io/ai/llama3.2:latest

# Disable unused OpenAI auto-configurations
spring.ai.openai.audio.speech.enabled=false
spring.ai.openai.audio.transcription.enabled=false
spring.ai.openai.image.enabled=false
spring.ai.openai.embedding.enabled=false